stages:
  - dast

baseline-scan:
  stage: dast
  image: registry.gitlab.com/gitlab-org/security-products/zaproxy
  tags:
    - dind_lms
  variables:
    website: "https://example.com"
  allow_failure: true
  before_script:
    - lsb_release -cs
    - apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu$(lsb_release -cs)stable"
    - apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
  script:
    - cat /etc/*release*
    - docker run hello-world
    # - mkdir /zap/wrk/
    # - /zap/zap-baseline.py -J gl-dast-report.json -t $website || true
    # - cp /zap/wrk/gl-dast-report.json .
  # artifacts:
  #   reports:
  #     dast: gl-dast-report.json
