stages:
  - dast

baseline-scan:
  stage: dast
  image: registry.gitlab.com/gitlab-org/security-products/zaproxy
  variables:
    website: "https://example.com"
  allow_failure: true
  script:
    - cat /etc/*release*
    - docker
    # - mkdir /zap/wrk/
    # - /zap/zap-baseline.py -J gl-dast-report.json -t $website || true
    # - cp /zap/wrk/gl-dast-report.json .
  # artifacts:
  #   reports:
  #     dast: gl-dast-report.json
